services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    SkillDisplay\SkilldisplayContent\:
        resource: '../Classes/*'

    SkillDisplay\SkilldisplayContent\Frontend\DataProcessing\:
        resource: '../Classes/Frontend/DataProcessing/*'
        public: true

    skilldisplay.settings:
        class: 'SkillDisplay\PHPToolKit\Configuration\Settings'
        factory:
            - '@SkillDisplay\SkilldisplayContent\SettingsFactory'
            - 'createFromCurrentSiteConfiguration'

    SkillDisplay\PHPToolKit\Configuration\Settings:
        alias: '@skilldisplay.settings'

    SkillDisplay\PHPToolKit\Api\Skill:
        arguments:
            $settings: '@skilldisplay.settings'

    SkillDisplay\PHPToolKit\Api\SkillSet:
        arguments:
            $settings: '@skilldisplay.settings'

    SkillDisplay\PHPToolKit\Api\Campaigns:
        arguments:
            $settings: '@skilldisplay.settings'

    SkillDisplay\PHPToolKit\Verification\Link:
        public: true
        arguments:
            $settings: '@skilldisplay.settings'

    SkillDisplay\SkilldisplayContent\Backend\Preview:
        public: true

    SkillDisplay\Typo3Extension\TcaEnhancer:
        public: true
